### ISSUE TITLE
Problems with new interface in 3.0

### ISSUE THREAD

**Issue by Elserjo** [Nicotine-Plus/nicotine-plus#1033]
**My operating system**: Arch Linux 5.11.10
**My desktop environment**: Mate 1.24

Hello. I have faced several problems with new interface:
1) Problem with tray icon. It just does not show in my tray dock.
2) Interface is laggy, and first launch takes too long. 
3) I can not connect to soulseek network, it just writes that i am offline. 
4) Some buttons didn't work.

I have also made screen capture. Hope it helps. 
On 2.2.2-1 i have not faced this problems. 

https://disk.yandex.ru/i/loyzwCY4M0N3pA

Here some errors from terminal: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/downloads.py", line 150, in update_download_filters
    error = _("Error: %(num)d Download filters failed! %(error)s ", {'num': len(failed), 'error': errors})
TypeError: gettext() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2781, in do_activate
    NicotineFrame(
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 264, in __init__
    self.downloads = Downloads(self, self.DownloadsTabLabel)
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/downloads.py", line 82, in __init__
    self.update_download_filters()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/downloads.py", line 155, in update_download_filters
    log.add(_("Error: Download Filter failed! Verify your filters. Reason: %s", e))
TypeError: gettext() takes 2 positional arguments but 3 were given

(org.nicotine_plus.Nicotine:3094): Gtk-WARNING **: 21:09:18.416: gtk_window_set_titlebar() called on a realized window
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1463, in on_switch_page
    self.downloads.update(forceupdate=True)
AttributeError: 'NicotineFrame' object has no attribute 'downloads'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 892, in on_connect
    self.tray.set_connected(True)
AttributeError: 'NicotineFrame' object has no attribute 'tray'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 892, in on_connect
    self.tray.set_connected(True)
AttributeError: 'NicotineFrame' object has no attribute 'tray'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2573, in on_settings_updated
    self.downloads.update_download_filters()
AttributeError: 'NicotineFrame' object has no attribute 'downloads'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1827, in on_search
    self.searches.on_search()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/search.py", line 125, in on_search
    feedback = self.frame.np.pluginhandler.outgoing_global_search_event(text)
AttributeError: 'NoneType' object has no attribute 'outgoing_global_search_event'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 892, in on_connect
    self.tray.set_connected(True)
AttributeError: 'NicotineFrame' object has no attribute 'tray'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1463, in on_switch_page
    self.downloads.update(forceupdate=True)
AttributeError: 'NicotineFrame' object has no attribute 'downloads'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 1459, in on_switch_page
    self.uploads.update(forceupdate=True)
AttributeError: 'NicotineFrame' object has no attribute 'uploads'

```

**Comment by mathiascode** [comment]
Thanks, this should be fixed in unstable now. Could you verify that this is the case for you? https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md

**Comment by Elserjo** [comment]
> Thanks, this should be fixed in unstable now. Could you verify that this is the case for you? https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md

i have tested, and it works pretty well. Thank you).
