### ISSUE TITLE
Can't save files.db: [Errno 13]

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1352]
Nicotine+ version: 3.0.5.dev1

### Describe the bug
In case it's just me experiencing this, on startup:

```
13:59:05 [Stat] Loading local icons, using path C:\Program Files\Nicotine+\files
13:59:05 Loading plugin handler
13:59:05 Enabled plugin Multi Paste
13:59:05 Listening on port 2234
13:59:05 Rescanning normal shares...
13:59:06 Rescanning buddy shares...
13:59:06 15 folders found before rescan, rebuilding...
13:59:06 Can't save files.db: [Errno 13] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\files.db\\data'
13:59:06 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\user\AppData\Roaming\nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "pynicotine/shares.py", line 102, in run
  File "pynicotine/shares.py", line 192, in rescan_dirs
  File "pynicotine/shares.py", line 463, in get_files_index
  File "pynicotine/shares.py", line 52, in shelve_open_semidbm
  File "semidbm/db.py", line 361, in open
  File "semidbm/db.py", line 40, in __init__
  File "semidbm/db.py", line 264, in _load_db
  File "semidbm/db.py", line 271, in _remove_files_in_dbdir
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\fileindex.db\\data'
13:59:06 3537 folders found before rescan, rebuilding...
13:59:13 Can't save buddyfiles.db: [Errno 13] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\buddyfiles.db\\data'
13:59:13 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\user\AppData\Roaming\nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "pynicotine/shares.py", line 102, in run
  File "pynicotine/shares.py", line 192, in rescan_dirs
  File "pynicotine/shares.py", line 463, in get_files_index
  File "pynicotine/shares.py", line 52, in shelve_open_semidbm
  File "semidbm/db.py", line 361, in open
  File "semidbm/db.py", line 40, in __init__
  File "semidbm/db.py", line 264, in _load_db
  File "semidbm/db.py", line 271, in _remove_files_in_dbdir
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\buddyfileindex.db\\data'
```

After delete of *.dbs and re-run:

```
14:02:48 [Stat] Loading local icons, using path C:\Program Files\Nicotine+\files
14:02:48 Loading plugin handler
14:02:48 Enabled plugin Multi Paste
14:02:48 Listening on port 2234
14:02:49 Rescanning normal shares...
14:02:49 Rescanning buddy shares...
14:02:49 0 folders found before rescan, rebuilding...
14:02:49 0 folders found before rescan, rebuilding...
14:02:51 Can't save files.db: [Errno 13] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\files.db\\data'
14:02:51 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\user\AppData\Roaming\nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "pynicotine/shares.py", line 102, in run
  File "pynicotine/shares.py", line 192, in rescan_dirs
  File "pynicotine/shares.py", line 463, in get_files_index
  File "pynicotine/shares.py", line 52, in shelve_open_semidbm
  File "semidbm/db.py", line 361, in open
  File "semidbm/db.py", line 40, in __init__
  File "semidbm/db.py", line 264, in _load_db
  File "semidbm/db.py", line 271, in _remove_files_in_dbdir
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\nicotine\\fileindex.db\\data'
```

**Comment by Inso-m-niaC** [comment]
have you checked the task manager for multiple instances of nicotine running?

**Comment by redactedscribe** [comment]
Just checked. No instances running when I launch, and I still get the error. Forgot to mention I was previously using https://github.com/Nicotine-Plus/nicotine-plus/commit/6c93361e1fb2ccbf6af25acd588e581f17c6873d (2 days since commit), and just tried out the latest https://github.com/Nicotine-Plus/nicotine-plus/commit/e2f730ad30b159364186acc093a149a22ae0696b which is when the bug started happening.

**Comment by Inso-m-niaC** [comment]
14:22:12 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\Gaming\AppData\Roaming\nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "pynicotine/shares.py", line 102, in run
  File "pynicotine/shares.py", line 192, in rescan_dirs
  File "pynicotine/shares.py", line 463, in get_files_index
  File "pynicotine/shares.py", line 52, in shelve_open_semidbm
  File "semidbm/db.py", line 361, in open
  File "semidbm/db.py", line 40, in __init__
  File "semidbm/db.py", line 264, in _load_db
  File "semidbm/db.py", line 271, in _remove_files_in_dbdir
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Gaming\\AppData\\Roaming\\nicotine\\buddyfileindex.db\\data'

On the latest commit.

**Comment by Inso-m-niaC** [comment]
I have tried each commit in reverse order and the error stopped on this commit https://github.com/Nicotine-Plus/nicotine-plus/pull/1351

**Comment by Inso-m-niaC** [comment]
Well, this is the last one that works for me https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/765497653
