### ISSUE TITLE
GtkTreeView column header context menus are out-of-context on MX Linux Continuum 18.3

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1492]
### Describe the problem
The right-click context menu that appears from the File Search Results column header in the GtkTreeView widget displays a list of open search tabs, but this is not expected nor useful in this context.

Plenty other methods of switching between tabs are provided, that are more logical for the user, so this method of selection is not required here.

### Describe the solution you'd like
Perhaps a context menu that provides useful functions that relate to column layout or sorting order would be useful here?

The context menu itself is useful on the search tabs bar, so it should still exist there. Perhaps it could also be made accessible from the blank space in the Results header, to match the context menu of the Results Count button.

### Additional context
See also related issue #1491 for other ideas about improving the widget's implementation.

**Comment by mathiascode** [comment]
I'm not sure what's going on here. The column header right-click menu displays a list of all columns, with the option to hide/show them.

![](https://user-images.githubusercontent.com/8754153/131225832-abf02861-9402-411b-b413-030a00a6ec7f.png)

**Comment by slook** [comment]
Nope, that's not what I saw on my MX18 system in 3.1.2.dev1  •  GTK 3.22.11  .deb run from local git folder

![nicotine-plus issue 1492 GtkTreeView header context menu incorrect](https://user-images.githubusercontent.com/88614182/131226822-8a1aa00c-6862-4151-9e12-6de67f8833a0.png)

The problem is gone after restart, intermittent I only experienced one time after playing around with columns I must have caused an error condition somehow, who knows. I'll test if I can find what made it happen.

**Comment by slook** [comment]
Yes, this is a reproducible bug, please change this issue to a Bug...

1. Drag move the Folder column header to the first left-most position in the Results Table, then;
2. Right-Click on any header other than Folder (right-clicking on the Folder header works as expected).

![nicotine-plus issue 1492 GtkTreeView header context menu incorrect after moving folder column](https://user-images.githubusercontent.com/88614182/131227131-428a3540-6715-4459-84e1-f857e68da0df.png)

**Comment by mathiascode** [comment]
It doesn't seem to matter how many searches you've done. When testing MX Linux 18.3, the behavior is inconsistent. Sometimes everything works fine, other times seemingly random columns break, even if User is the first column. I can't reproduce this on my main system though.

Does right-clicking the column headers on the downloads/uploads pages do anything? The menu never opens for me there.

**Comment by slook** [comment]
```
Exception in thread NetworkThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/sli/Git/nicotine-plus/pynicotine/slskproto.py", line 1603, in run
    self.write_data(conn_obj)
  File "/home/sli/Git/nicotine-plus/pynicotine/slskproto.py", line 1381, in write_data
    if conn_obj.fileupl is not None and conn_obj.fileupl.offset is not None:
AttributeError: 'Connection' object has no attribute 'fileupl'

```

**Comment by slook** [comment]
> Does right-clicking the column headers on the downloads/uploads pages do anything? The menu never opens for me there.

No me neither, there is no context menu there for me.

**Comment by slook** [comment]
Edge case. Legacy. On my MX19 VM the problem does not occur with the stock GTK3 theme.

**Comment by slook** [comment]
@mathiascode  I think due to the age and quirkiness of the affected system, it's fair to mark this issue as WontFix

**Comment by mathiascode** [comment]
If we're going to support old systems, we should support them properly. I'll have to check if this issue is exclusive to MX Linux, or if older Ubuntu and Debian versions are affected too.

**Comment by mathiascode** [comment]
> Nicotine+ started spamming the debug log with remote messages and connection error I heard fan spin whilst playing with the columns, then found this error...
> 
> ```
> Exception in thread NetworkThread:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/home/sli/Git/nicotine-plus/pynicotine/slskproto.py", line 1603, in run
>     self.write_data(conn_obj)
>   File "/home/sli/Git/nicotine-plus/pynicotine/slskproto.py", line 1381, in write_data
>     if conn_obj.fileupl is not None and conn_obj.fileupl.offset is not None:
> AttributeError: 'Connection' object has no attribute 'fileupl'
> ```
> 
> Probaby unrelated but seemed to be triggered by file search for my username, then the column sort, after sitting idle fine no problem then fan spin.

Have you encountered this again? As far as I can tell, the only way this error would be possible is if there were two server connection objects somehow.

**Comment by slook** [comment]
> this error would be possible is if there were two server connection objects somehow.

Ah, well maybe I was running N+ in a VM and also on the host. Obviously this shares same IP via NAT. Perhaps the server got confused by that or something. Interesting there was some chat in the nicotine room earlier, suggesting there was some port scanning going on. Presently there is discussion about network security. The timing was just a coincidence I think.

> I'll have to check if this issue is exclusive to MX Linux

I appreciate your diligence. I have checked on MX-19.4 Patito Feo and it's fine on there.

Please bear in mind that the particular MX-18.3 Continuum installation in question has been migrated again and again ever since MX-16 Metamorphosis and through MX-17 Horizon, longevity testing was the objective and still is. Whilst it's package updates have remained reliable from the stable branch and issues are rare, the environment is long-in-the-tooth to say the least!

It is highly unusual and interesting however, like the shortcut key binding issue we discovered in issue #1485, that this quirk has emerged with the GTK widget. I hope that discovery of such things is helpful and not a hindrance to you in ensuring the stability of N+.

**Comment by slook** [comment]
The only console warnings I got since then are GTK related:

```
[2021-08-28 21:00:16] [Search] User JD_DJ is searching for "groove", returning 1 results

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:00:25.956: Allocating size to GtkButton 0x5568ea322180 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:00:25.956: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
[2021-08-28 21:01:36] [Search] User evilnoodle9 is searching for "oden fatzo", returning 2 results
```

```
[2021-08-28 21:22:44] [Search] User willster146 is searching for "loveless", returning 1 results

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:01.861: Allocating size to GtkButton 0x5568eac16880 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:01.861: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:04.224: Allocating size to GtkButton 0x5568eac16a40 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:04.224: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:08.731: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:16.691: Allocating size to GtkButton 0x5568eac16500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:23:16.691: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
[2021-08-28 21:23:23] [Search] User Messie is searching for "lazy", returning 1 results

```

```
[2021-08-28 21:28:10] [Search] User Jaygo 71 is searching for "intro", returning 1 results

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:28:18.348: Allocating size to GtkButton 0x5568ea322500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:28:18.349: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:28:19.799: Allocating size to GtkButton 0x5568ea3226c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 21:28:19.799: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
[2021-08-28 21:28:48] [Search] User alexlima is searching for "artbat", returning 1 results

```

```
[2021-08-28 23:22:43] [Search] User willster146 is searching for "loveless", returning 1 results

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 23:23:00.415: Allocating size to GtkButton 0x5568ea322500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 23:23:00.415: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 23:23:05.598: Allocating size to GtkButton 0x5568ea197dc0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:3124): Gtk-WARNING **: 23:23:05.599: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
[2021-08-28 23:23:19] [Search] User cigga-weed is searching for "hannah", returning 1 results

```

**Comment by mathiascode** [comment]
The column menu issue happens in older GTK versions, and the `gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed` error also appears in those versions. Smells like an old GTK bug, might have to figure out some hack to work around this.

GtkTreeView can be quirky sometimes, and was essentially broken in GTK 4 (some issues were fixed after I reported them). A replacement widget was introduced in GTK 4, but it will take years before it becomes relevant.

**Comment by slook** [comment]
Let me know if you want anything in particular from my system that may help you, events logs or etc?

**Comment by mathiascode** [comment]
> The only console warnings I got since then are GTK related:

Do you have any narrow columns? Try making them wider and see if the warnings disappear.

**Comment by slook** [comment]
Yeh I had the 'In Queue' narrow so it just said 'In Q' I made it wider now, no errors appears whilst the adjustment was made nor since.

The warnings upon application start (even after having are as follows:

```
user@machine:~/Git/nicotine-plus$ ./nicotine

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.348: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.348: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.348: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.348: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed
[2021-08-29 00:48:35] [Misc] Loading plugin handler
[2021-08-29 00:48:35] Connecting to server.slsknet.org:2242

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.480: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.481: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.484: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed

(org.nicotine_plus.Nicotine:10884): Gtk-CRITICAL **: 00:48:35.485: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed
[2021-08-29 00:48:35] Listening on port 2234
[2021-08-29 00:48:35] Connected to server server.slsknet.org:2242, logging in...

```

So it's only those 'Critical' GTK messages, no 'Warnings'. Pretty consistant upon every start... 3 or 4 before Loading plugin handler... then 50 or so after that.

**Comment by slook** [comment]
I am running from a local Git folder, so perhaps I am missing some dependencies?...

```
user@machine:~$ dpkg -l libgtk[0-9]* | grep ^i
ii  libgtk2-ex-simple-list-perl 0.50-2       all          simple interface to Gtk2's complex MVC list widget
ii  libgtk2-imageview-perl      0.05-2+b3    amd64        Perl bindings for the GtkImageView image viewer widget
ii  libgtk2-perl                2:1.2499-1   amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64           2.24.31-2    amd64        GTK+ graphical user interface library
ii  libgtk2.0-common            2.24.31-2    all          common files for the GTK+ graphical user interface library
ii  libgtk3-perl                0.030-1      all          Perl bindings for the GTK+ graphical user interface library
sli@ThinkPadX220:~$ dpkg -l libgtk3[0-9]* | grep ^i
dpkg-query: no packages found matching libgtk3[0-9]*
user@machine:~$ 

```

/home/user/Pictures/nicotine-plus/ThinkPadX220 GTK3 related packages installed.png
![ThinkPadX220 GTK3 related packages installed](https://user-images.githubusercontent.com/88614182/131234124-1dff24ff-ffd4-4628-8d35-740df17dc092.png)

Let me know if you want me to try installing anything extra onto the machine?

**Comment by mathiascode** [comment]
No need to install anything (https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEPENDENCIES.md is all you need). These critical errors appear in GTK 3.22.11 and below, nothing in newer GTK versions, but I don't know what causes it yet.

**Comment by slook** [comment]
It may or may not be interesting to know, that I experience a problem with Opera browser window maximize button not working. Opera forces it's own GTK3 theme. It does un-maximize, but then won't maximize again unless I drag it's window to the top edge of the screen (XFCE window manager's snapping feature is configured to do this). Previously, I had thought it was a Opera bug.

What is interesting, is that I experience exactly the same issue with the maximize button in Nicotine+ it will un-maximize fine, but then won't maximize again unless I snap it with the drag to screen top edge.

This confirms to me, that the machine does infact have issues with GTK3, and it is not the fault of Nicotine+

Perhaps, these issues are loosely related in some way. Just a thought.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/7999c33b34dd0eb2b1e140616e6758ee6fafc191 should fix the critical errors and the menu issues. Can you confirm?

**Comment by slook** [comment]
Yes! The context menus all work properly :-)

And the log is free from Critical errors too.

Only these two Warning errors (similar in both MX18 and MX19):

```
[2021-08-29 03:02:10] Finished rescanning public shares

(org.nicotine_plus.Nicotine:14397): Gtk-WARNING **: 03:02:33.217: Allocating size to GtkButton 0x5647e74c4500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(org.nicotine_plus.Nicotine:14397): Gtk-WARNING **: 03:02:33.218: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
[2021-08-29 03:04:38] [Search] User corbyem52 is searching for "james", returning 2 results
```

Nice job! It's so nice being able to show/hide columns.

**Comment by slook** [comment]
Amazing you can actually "smell" bugs... https://github.com/nicotine-plus/nicotine-plus/issues/1492#issuecomment-907703486 LOL :-D

Thankyou Thankyou Thankyou :-D

**Comment by mathiascode** [comment]
You're welcome. :)

It's nice to see that everything works fine from GTK 3.18 to 4.2 now, without any large hacks or version-specific implementations needed.
