### ISSUE TITLE
Upgrading from 3.0.6 to 3.1.2.dev1 causes Serious [Errno 20] corrupted database index unresolved (Setup)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1519]
Nicotine+ version: 3.0.6 (Stable) > 3.1.2 (Unstable), other previous versions also (yet to be tested).
Operating System/Distribution: MX Linux 18.3 Continuum (Debian Stretch 9 LTS), probably others.
Python versions: 2.7; 3.5; 3.7
 
### Describe the bug
In the process of testing migration from 3.0.6 Stable to 3.1.2 Unstable, a "**Serious error**" is always encountered that prevents the end-user's files from being shared as expected, until a complex manual intervention is done to remedy the issue on the target machine.

Hidden `.db` folders appear in `/home/user/.nicotine/` that didn't exist before (they were flat files in the previous version), and it seems that this variation in structure is not handled gracefully during the migration process.

Release of 3.1.2 into the Stable branch must be blocked until this issue is resolved, tested then closed but only after further verification. This scenario, and probably many other similar migration scenarios, is guaranteed to brick the application from working correctly first-time for many existing users who are going to be upgrading (new users will not be affected by this bug).

### Expected behavior
Setup or first-run should be able to detect if any alterations are required in locally stored database indexes that are already in the user's profile path, so that either the package installer, the application (or both) can then apply any transitional changes silently in the background, in a such a way that the upgraded application will function as intended upon first run.

Perhaps, a fall-back recovery mechanism should be built-in that simply deletes the offending index *.db files/folders from the local profile, in order to allow a successful Rescan to take place as normal? This process should be logged in the background but no errors nor warnings need to be thrown up, because actual user content would remain untouched, of course.

- **If any minor depreciated index entries or user preferences from <3.0.x need to get lost, then so be it.**

- **The only critical runtime settings that must be retained are items like the names of the previously defined Virtual Folders and the local path of the Shared Folders (fortunately these values are known during first-run** (see error log below)).

- **Backward compatibility should also be considered, incase the user wishes/needs to downgrade in the future for any reason.**

- **Ideally, all data created by previous versions should be compatible without needing to add/remove anything manually.**

I am unsure if this problem may be related to an issue with the previous PIP3 and Flatpak installations? I have seen similar Python errors during many installations (I had previously thought it was a dependency lacking from the environment) but the application runs with no issues once installed. Note that many users were unable to run the .deb package until recently (see #1488), so the migration scenario currently being tested may become very common in the future.

### Steps to reproduce the bug

1. Install 3.0.6 Stable (PIP3),
2. Install 3.1.2 Unstable,
3. The Public Shares are borked,
4. The Rescan Public Shares funtions have no effect (the error persists),
5. Then, manual deletion of the hidden .db files/folders from the filesystem is required by the end-user,
6. Finally, the database correctly rebuilds itself without issue, but only after difficulties in the above step.
- Note: No important user data is lost, but this would be seriously inconvenient for an end-user to figure out.

### Additional context
_gdbm packages installed (default paths on this target machine):_
```
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgdbm.so.3
/usr/lib/x86_64-linux-gnu/libgdbm.so.3.0.0
/usr/lib/x86_64-linux-gnu/libgdbm_compat.so.3
/usr/lib/x86_64-linux-gnu/libgdbm_compat.so.3.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libgdbm3
/usr/share/doc/libgdbm3/changelog.Debian.gz
/usr/share/doc/libgdbm3/changelog.gz
/usr/share/doc/libgdbm3/copyright
```

_Console output:_
```
user@machine:~/Git/nicotine-plus$ python /usr/local/lib/python3.5/dist-packages/semidbm/db.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 14, in <module>
    from semidbm.exceptions import DBMLoadError, DBMChecksumError, DBMError
ModuleNotFoundError: No module named 'semidbm'

user@machine:~/Git/nicotine-plus$ sudo update-alternatives --config python
There are 3 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python3.7   3         auto mode
  1            /usr/bin/python2.7   1         manual mode
  2            /usr/bin/python3.5   2         manual mode
  3            /usr/bin/python3.7   3         manual mode

user@machine:~/Git/nicotine-plus$ python --version
Python 3.7.2

user@machine:~/Git/nicotine-plus$ ./nicotine
[2021-09-02 15:11:46] [Misc] Loading plugin handler
[2021-09-02 15:11:46] Connecting to server.slsknet.org:2242
[2021-09-02 15:11:46] Listening on port 2231
[2021-09-02 15:11:46] Connected to server server.slsknet.org:2242, logging in...
[2021-09-02 15:11:46] [Conn] We have no parent, requesting a new one
[2021-09-02 15:11:47] Rescanning normal shares...
[2021-09-02 15:11:47] 1686 privileged users
[2021-09-02 15:11:47] Rescanning buddy shares...
[2021-09-02 15:11:47] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
[2021-09-02 15:11:47] 8 folders found before rescan, rebuilding...
[2021-09-02 15:11:47] 8 folders found after rescan
[2021-09-02 15:11:47] Serious error occurred while rescanning shares. If this problem persists, delete /home/user/.nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 99, in run ("mtimes", os.path.join(self.config.data_dir, "buddymtimes.db"))
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 627, in load_shares 'names': '\n'.join(errors)
  File "/home/user/Git/nicotine-plus/pynicotine/logfacility.py", line 65, in add levels = config.sections["logging"]["debugmodes"]
KeyError: 'debugmodes'

[2021-09-02 15:11:47] Finished rescanning public shares
[2021-09-02 15:11:47] Failed to process the following databases: /home/user/.nicotine/buddyfiles.db
/home/user/.nicotine/buddystreams.db
/home/user/.nicotine/buddywordindex.db
/home/user/.nicotine/buddyfileindex.db
/home/user/.nicotine/buddymtimes.db
[2021-09-02 15:11:47] Traceback (most recent call last):
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 614, in load_shares shares[destination] = shelve.open(shelvefile, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 52, in shelve_open_semidbm return shelve.Shelf(semidbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 357, in open return _SemiDBM(filename, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 40, in __init__ self._load_db()
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 48, in _load_db self._index = self._load_index(self._data_filename)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 56, in _load_index self._write_headers(filename)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 64, in _write_headers with _open(filename, 'wb') as f: NotADirectoryError: [Errno 20] Not a directory: '/home/user/.nicotine/buddymtimes.db/data'

[2021-09-02 15:11:47] Shared files database seems to be corrupted, rescan your shares
[2021-09-02 15:11:47] Failed to process the following databases: /home/user/.nicotine/buddyfiles.db
/home/user/.nicotine/buddystreams.db
/home/user/.nicotine/buddywordindex.db
/home/user/.nicotine/buddyfileindex.db
/home/user/.nicotine/buddymtimes.db
[2021-09-02 15:11:47] Traceback (most recent call last):
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 616, in load_shares shares[destination] = shelve.open(shelvefile, flag='n', protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/user/Git/nicotine-plus/pynicotine/shares.py", line 52, in shelve_open_semidbm return shelve.Shelf(semidbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 361, in open return _SemiDBMNew(filename, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 40, in __init__ self._load_db()
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 265, in _load_dbsuper(_SemiDBMNew, self)._load_db()
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 48, in _load_dbself._index = self._load_index(self._data_filename)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 56, in _load_indexself._write_headers(filename)
  File "/usr/local/lib/python3.5/dist-packages/semidbm/db.py", line 64, in _write_headers with _open(filename, 'wb') as f:
NotADirectoryError: [Errno 20] Not a directory: '/home/user/.nicotine/buddymtimes.db/data'

[2021-09-02 15:11:47] Shared files database seems to be corrupted, rescan your shares
```
_Note: The 'Rescan Public Shares' function has no effect (the error persists)_

![nicotine-plus Upgrade causes  Errno20  database corrupted](https://user-images.githubusercontent.com/88614182/131883338-5a13e666-f28a-4965-bc2a-78b9d1d6d969.png)

_Note: After manual deletion of all the selected (above), everything is fine, even my preferences are still remembered :-)_

- No important user data is lost, but this would be seriously inconvenient for an end-user to figure out.

**Comment by mathiascode** [comment]
Shares have not changed from 3.0.6 to 3.1.2, but this can happen if the database library changes from gdbm to semidbm or vice versa, since they are not compatible with each other. This would be a rather rare issue, but we should probably delete the .db files/folders if this happens.

**Comment by slook** [comment]
> we should probably delete the .db files/folders if this happens

I agree that would be a suitable solution in this rare case.

Can we add a debug notice to the log if your proposed fall-back is invoked?
