### ISSUE TITLE
List of GTK 4 regressions

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#1554]
- Rubberband selection broken (select and drag in GtkTreeView)
  - Unlikely to be fixed anytime soon, attempt a port to GtkColumnView for the GTK 4 version of Nicotine+
  - Upstream report: https://gitlab.gnome.org/GNOME/gtk/-/issues/3985
- No scrolling in dropdown menus (GtkComboBox)
  - Upstream report: https://gitlab.gnome.org/GNOME/gtk/-/issues/3674
- No support for spell checking
  - Support is planned in GTK 4, but will probably not be implemented soon
  - Upstream report: https://gitlab.gnome.org/GNOME/gtk/-/issues/3814
- No support for tray icons
  - Linux: AppIndicator is currently missing GTK 4 support: https://github.com/AyatanaIndicators/libayatana-appindicator/issues/22
  - Windows: do we need tray icons? Find an alternative to GtkStatusIcon? (use Windows API directly?)
  - macOS: nothing to do, since tray icons are not used

To test the GTK 4 version of Nicotine+ in a Linux/BSD environment, start Nicotine+ using:
`NICOTINE_GTK_VERSION=4 nicotine`

**Comment by 82d** [comment]
```
$NICOTINE_GTK_VERSION=4 nicotine
Traceback (most recent call last):
  File "/usr/local/bin/nicotine", line 24, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/pynicotine/__init__.py", line 232, in run
    return run_gui(core, trayicon, hidden, bindip, port, ci_mode, multi_instance)
  File "/usr/local/lib/python3.8/site-packages/pynicotine/gtkgui/__init__.py", line 52, in run_gui
    error = check_gui_dependencies()
  File "/usr/local/lib/python3.8/site-packages/pynicotine/gtkgui/__init__.py", line 41, in check_gui_dependencies
    from gi.repository import Gtk  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/local/lib/python3.8/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/local/lib/python3.8/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/local/lib/python3.8/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'

```

**Comment by mathiascode** [comment]
Version requirements are now checked on startup (GTK >= 4.4.0 and PyGObject >= 3.40.0 is required).

**Comment by mathiascode** [comment]
I'll close this for now, since the remaining issues are not exclusive to Nicotine+.

**Comment by francisuk1989** [comment]
Just wanted to give a update on the situation, I'm running GTK 4.6.0

@mathiascode There is missing logo 

[francis@ArchLinux nicotine-plus]$ NICOTINE_GTK_VERSION=4 ./nicotine
[2022-02-14 03:00:51] Loading GTK 4.6.0
[2022-02-14 03:00:52] Loading Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
[2022-02-14 03:00:52] Loading Nicotine+ 3.2.2.dev1
[2022-02-14 03:00:52] Listening on port: 22342
[2022-02-14 03:00:52] Loading plugin system
[2022-02-14 03:00:52] You need to specify a username and password before connecting…
[2022-02-14 03:00:54] UPnP: Failed to forward external port 22342: UPnP is not available on this network
[2022-02-14 03:05:19] Connecting to server
**(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:19.501: GtkGizmo 0x55eb35a56640 (progress) reported min width -2, but sizes must be >= 0**
[2022-02-14 03:05:19] Rescanning shares…
[2022-02-14 03:05:19] 0 folders found before rescan, rebuilding…
[2022-02-14 03:05:19] Connected to server server, logging in…
[2022-02-14 03:05:20] 1853 privileged users
[2022-02-14 03:05:20] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.

**(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:26.253: Broken accounting of active state for widget 0x55eb3783ee40(GtkPopoverContent)

(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:26.253: Broken accounting of active state for widget 0x55eb37a2a6a0(GtkPopoverMenu)
[2022-02-14 03:05:35] Rescan complete: 166 folders found

(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:35.698: Broken accounting of active state for widget 0x55eb3783ee40(GtkPopoverContent)

(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:35.698: Broken accounting of active state for widget 0x55eb37a2a6a0(GtkPopoverMenu)

(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:37.615: Broken accounting of active state for widget 0x55eb37427430(GtkPopoverContent)

(org.nicotine_plus.Nicotine:35112): Gtk-WARNING **: 03:05:37.615: Broken accounting of active state for widget 0x55eb37a2a460(GtkPopoverMenu)**

**Comment by mathiascode** [comment]
@francisuk1989 I've seen the issue with missing icons on someone else's system too. Unfortunately, we can't control this in Nicotine+, something on your system causes GTK 4 to not set an icon theme.

Regarding the other warnings, do you remember what you did for them to appear? Was this a longer session where you opened many context menus?

**Comment by mathiascode** [comment]
Closing in favor of #2014
