### ISSUE TITLE
(world) flags missing at startup / and buddy list 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#161]
when starting nic+ some users without any flag 
if disconect reconect they display world flag ( even if it should display other country if you check ip , this one ok)

in buddy list also but disconect/reconect is without effect 

https://imgur.com/a/dPX1a6L    

pic1 startup
pic2 disconnect/reconnect
pic3 buddylist > even mine is missing in buddylist

**Comment by mathiascode** [comment]
What's interesting is that the buddy list flag is correct when starting the program, but turns into a world flag once the list has been refreshed. I'm suspecting a bytes/string mismatch somewhere.

**Comment by mathiascode** [comment]
@zniavre Can you test https://github.com/Nicotine-Plus/nicotine-plus/pull/163 and see if it fixes the issue for you? I had success myself.

**Comment by zniavre** [comment]
wich branch ? please


2020-05-22 14:40 UTC+02:00, Mat <notifications@github.com>:
> @zniavre Can you test
> https://github.com/Nicotine-Plus/nicotine-plus/pull/163 and see if it fixes
> the issue for you? I had success myself.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nicotine-Plus/nicotine-plus/issues/161#issuecomment-632670671


-- 
On peut y ajouter tout le fûmier qu'on veut , pour un chêne
centenaire,   faut cent ans ....

**Comment by mathiascode** [comment]
`git clone -b flagfix https://github.com/mathiascode/nicotine-plus.git`

**Comment by zniavre** [comment]
so wait a second i need to install git stuff first ...   im not using it since svn was easy and im too old to use something else  :o)

**Comment by zniavre** [comment]
Traceback (most recent call last):
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/gtkgui/frame.py", line 1371, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/pynicotine.py", line 1027, in AddUser
    self.GetUserStats(msg)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/pynicotine.py", line 1192, in GetUserStats
    self.userlist.GetUserStats(msg)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/gtkgui/userlist.py", line 439, in GetUserStats
    flag = "flag_" + msg.country
TypeError: can only concatenate str (not "bytes") to str
Traceback (most recent call last):
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/gtkgui/frame.py", line 1371, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/pynicotine.py", line 1027, in AddUser
    self.GetUserStats(msg)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/pynicotine.py", line 1192, in GetUserStats
    self.userlist.GetUserStats(msg)
  File "/home/zniavre/Documents/slsknic+/nicotine-plus/pynicotine/gtkgui/userlist.py", line 439, in GetUserStats
    flag = "flag_" + msg.country
TypeError: can only concatenate str (not "bytes") to str

**Comment by zniavre** [comment]
ho sorry posted this by error i wanted to pastebin it...

**Comment by zniavre** [comment]
but it works at least in rooms but looks like not in buddylist yet .

**Comment by mathiascode** [comment]
I found out the reason why the buddylist misbehaved (garbage data in country code due to reading the wrong position). Will push a fix shortly.

**Comment by mathiascode** [comment]
Can you update the branch and test again?

**Comment by mathiascode** [comment]
It's likely that the buddylist may still look broken for a few offline users due to invalid countries being written into the config. It should look fine once they are online again.

**Comment by zniavre** [comment]
yep it works i guess well  i agrree for buddylist missing flags until they reconnect
