### ISSUE TITLE
setup.py: DistutilsFileError

### ISSUE THREAD

**Issue by yochananmarqos** [Nicotine-Plus/nicotine-plus#164]
Running either `python setup.py build` or `python setup.py install` fails after the recent commit that added the plugins directory:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/nicotine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    copy_tree("plugins", os.path.join(sys.prefix, "share/nicotine/plugins"))
  File "/usr/lib/python3.8/distutils/dir_util.py", line 135, in copy_tree
    mkpath(dst, verbose=verbose)
  File "/usr/lib/python3.8/distutils/dir_util.py", line 73, in mkpath
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: could not create '/usr/share/nicotine': Permission denied
```

Manjaro GNOME
Python 3.83
setuptools 46.4.0

**Comment by mathiascode** [comment]
Fixed in https://github.com/Nicotine-Plus/nicotine-plus/pull/159, pending merge.

**Comment by yochananmarqos** [comment]
Ah, didn't notice there was a PR already. That fixes it, thanks.

**Comment by mathiascode** [comment]
This can be closed now.
