### ISSUE TITLE
IndexError at start on Debian Buster

### ISSUE THREAD

**Issue by eLvErDe** [Nicotine-Plus/nicotine-plus#202]
```
Traceback (most recent call last):
  File "/usr/bin/nicotine", line 276, in <module>
    run()
  File "/usr/bin/nicotine", line 252, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/frame.py", line 3729, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/frame.py", line 517, in __init__
    self.downloads = Downloads(self)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/downloads.py", line 100, in __init__
    cols[i].set_visible(self.frame.np.config.sections["columns"]["downloads_columns"][i])
IndexError: list index out of range
```

**Comment by eLvErDe** [comment]
The code crashing here is definitely suspicious:

```python        cols = frame.DownloadList.get_columns()

        for i in range(10):

            parent = cols[i].get_widget().get_ancestor(gtk.Button)
            if parent:
                parent.connect("button_press_event", PressHeader)

            # Read Show / Hide column settings from last session
            cols[i].set_visible(self.frame.np.config.sections["columns"]["downloads_columns"][i])
```

What about using len(cols) in the range statement ?

**Comment by mathiascode** [comment]
len(cols) won't work in this case, since the number of columns in the "downloads_columns" config option was incorrect before (9 instead of 10). We need to verify that the config is up-to-date in some good way.

**Comment by mathiascode** [comment]
Alternatively we can just catch the IndexError and do nothing. As soon as the user updates the column visibility, the config will correct itself.
