### ISSUE TITLE
CI on installed artifacts gives false positive (success when should be failure)

### ISSUE THREAD

**Issue by kiplingw** [Nicotine-Plus/nicotine-plus#228]
It looks like the Robot Framework's CI test that is run in autopkgtest is giving a false positive that the test passed when it should really be giving a true negative because of a runtime error. My guess is a system exit code may be not being checked properly.

```
...
autopkgtest [17:42:34]: test test-installed-artifacts.sh: [-----------------------
*** Installing test harness...
Collecting robotframework
  Downloading robotframework-3.2.1-py2.py3-none-any.whl (618 kB)
Installing collected packages: robotframework
Successfully installed robotframework-3.2.1
*** Launching Nicotine+ inside of dummy frame buffer...
==============================================================================
Nicotine :: Basic integration tests for nicotine+ Start nicotine both as a ...
==============================================================================
Run nicotine as shell command                                         
(nicotine:2861): dbind-WARNING **: 17:42:42.641: AT-SPI: Error retrieving accessibility bus address: orgs

(nicotine:2861): Gtk-WARNING **: 17:42:42.824: Error loading theme icon 'list-remove' for stock: Icon 'lu

(nicotine:2861): Gtk-WARNING **: 17:42:42.825: Error loading theme icon 'edit-clear' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.825: Error loading theme icon 'edit-clear' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.825: Error loading theme icon 'edit-redo' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.826: Error loading theme icon 'process-stop' for stock: Icon 'u

(nicotine:2861): Gtk-WARNING **: 17:42:42.826: Error loading theme icon 'list-remove' for stock: Icon 'lu

(nicotine:2861): Gtk-WARNING **: 17:42:42.827: Error loading theme icon 'edit-clear' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.827: Error loading theme icon 'edit-clear' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.827: Error loading theme icon 'process-stop' for stock: Icon 'u

(nicotine:2861): Gtk-WARNING **: 17:42:42.828: Error loading theme icon 'edit-clear' for stock: 

(nicotine:2861): Gtk-WARNING **: 17:42:42.828: Error loading theme icon 'document-open' for stock: Icon u

(nicotine:2861): Gtk-WARNING **: 17:42:42.829: Error loading theme icon 'view-refresh' for stock: Icon 'u

(nicotine:2861): Gtk-WARNING **: 17:42:42.829: Error loading theme icon 'view-refresh' for stock: Icon 'u

(nicotine:2861): Gtk-WARNING **: 17:42:42.829: Error loading theme icon 'view-refresh' for stock: Icon 'u

(nicotine:2861): Gtk-WARNING **: 17:42:42.829: Error loading theme icon 'list-add' for stock: Icon 'listu

(nicotine:2861): Gtk-WARNING **: 17:42:42.829: Error loading theme icon 'list-add' for stock: Icon 'listu
Traceback (most recent call last):
  File "/usr/bin/nicotine", line 255, in <module>
    run()
  File "/usr/bin/nicotine", line 231, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/frame.py", line 3611, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/frame.py", line 659, in __init__
    ConfigUnset = self.np.config.needConfig()
  File "/usr/lib/python3/dist-packages/pynicotine/config.py", line 454, in needConfig
    self.frame.settingswindow.SetSettings(self.sections)
AttributeError: 'NoneType' object has no attribute 'SetSettings'
Tue 17:42 Nicotine+ supports a country code blocker. This requires a (GPL'ed)
          library called GeoIP. You can find it here: C library:
          https://github.com/maxmind/geoip-api-c Python bindings:
          https://github.com/maxmind/geoip-api-python (the python bindings
          require the C library)
| PASS |
------------------------------------------------------------------------------
Nicotine :: Basic integration tests for nicotine+ Start nicotine b... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
...
```

This may be related to #122.

**Comment by mathiascode** [comment]
I don't think there's anything wrong in the test itself, but Nicotine+ keeps running if an exception is raised.

**Comment by kiplingw** [comment]
Thanks Mat. Was your PR for #232 also suppose to address making the test pass or to make sure that when it fails that it's detected as a failure?

**Comment by mathiascode** [comment]
Nope, the test is still broken.
