### ISSUE TITLE
Nicotine crash on many downloads, all folder downloads. 

### ISSUE THREAD

**Issue by WaterSibilantFalling** [nicotine-plus/nicotine-plus#2446]
Nicotine+ version:  
Operating System/Distribution:

- Linux 6.0.0-5-amd64 `#1` SMP PREEMPT_DYNAMIC Debian 6.0.10-2 (2022-12-01) x86_64 GNU/Linux
- Nicotine+ Version: 3.3.0.dev4
- GTK Version: 3.24.37
- Python Version: 3.11.2 (linux)

### Describe the bug

When saving a file, immediately after choosing a "save to" location, Nicotine crashes

```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 3.24.37
Python Version: 3.11.2 (linux)

Type: <class 'TypeError'>
Value: unknown type (null)
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/filechooser.py", line 116, in on_response
    self.callback(selected, self.callback_data)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1373, in on_download_folders_to_selected
    self.on_download_folders(download_location=selected)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1343, in on_download_folders
    user = self.resultsmodel.get_value(iterator, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Expected behavior

Be able to choose a save location, have the files download, and continue as normal. 

### Steps to reproduce the bug

Run nicotine
Search for and find some files
Try to download a folder containing some files

### Additional context
Screenshots, logs, stacktraces or relevant information.

I have not made any config changes. 

```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 3.24.37
Python Version: 3.11.2 (linux)

Type: <class 'TypeError'>
Value: unknown type (null)
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/filechooser.py", line 116, in on_response
    self.callback(selected, self.callback_data)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1373, in on_download_folders_to_selected
    self.on_download_folders(download_location=selected)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1343, in on_download_folders
    user = self.resultsmodel.get_value(iterator, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

terminal messages

```
 nicotine
[2023-03-16 18:50:32] Loading Python 3.11.2
[2023-03-16 18:50:32] Loading Nicotine+ 3.3.0.dev4
[2023-03-16 18:50:32] Loading GTK 3.24.37
[2023-03-16 18:50:33] Loaded plugin Nicotine+ Commands
[2023-03-16 18:50:33] Loading plugin system
[2023-03-16 18:50:33] Leech Detector: Ready to message leechers, require users have a minimum of 500 files in 1 shared public folders.
[2023-03-16 18:50:33] Loaded plugin Leech Detector
[2023-03-16 18:50:33] Loaded plugin Multi Paste
[2023-03-16 18:50:34] Listening on port: 2234
[2023-03-16 18:50:34] Connecting to server.slsknet.org:2242
[2023-03-16 18:50:34] Connected to server server.slsknet.org:2242, logging in…
[2023-03-16 18:50:34] NAT-PMP: External port 2234 successfully forwarded to local IP address 192.168.1.77 port 2234
[2023-03-16 18:50:34] 1927 privileged users
[2023-03-16 18:50:34] Rescanning shares…
[2023-03-16 18:50:34] 1992 folders found before rescan, rebuilding…
[2023-03-16 18:50:34] You have no Soulseek privileges. While privileges are active, your downloads will be queued ahead of those of non-privileged users.
[2023-03-16 18:50:39] Rescan complete: 1992 folders found

(org.nicotine_plus.Nicotine:31033): Gtk-CRITICAL **: 18:51:43.854: gtk_tree_store_get_value: assertion 'VALID_ITER (iter, tree_store)' failed
[2023-03-16 18:52:31] Quitting Nicotine+ 3.3.0.dev4, application closing…
[2023-03-16 18:52:32] Unloaded plugin Leech Detector
[2023-03-16 18:52:32] Unloaded plugin Multi Paste
[2023-03-16 18:52:32] Quit Nicotine+ 3.3.0.dev4, done!
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/filechooser.py", line 116, in on_response
    self.callback(selected, self.callback_data)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1373, in on_download_folders_to_selected
    self.on_download_folders(download_location=selected)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1343, in on_download_folders
    user = self.resultsmodel.get_value(iterator, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unknown type (null)

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/filechooser.py", line 116, in on_response
    self.callback(selected, self.callback_data)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1373, in on_download_folders_to_selected
    self.on_download_folders(download_location=selected)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py", line 1343, in on_download_folders
    user = self.resultsmodel.get_value(iterator, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unknown type (null)



```

**Comment by mathiascode** [comment]
Does Nicotine+ crash every time you try to download a folder? Any difference if you use `Download Folder(s)...` or `Download Folder(s) To...`?

**Comment by mathiascode** [comment]
Cannot reproduce. Let me know if this issue still occurs.
