### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object when trying to share files

### ISSUE THREAD

**Issue by sgreenden** [nicotine-plus/nicotine-plus#2560]
Nicotine+ version: 3.2.9 
Operating System/Distribution:
Debian 12, Flatpak

When I try to share files, I get the following message:
```
2023-06-29 20:32:08 Serious error occurred while rescanning shares. If this problem persists, delete /home/moon/.var/app/org.nicotine_plus.Nicotine/data/nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 113, in run
    new_mtimes, new_files, new_streams = self.rescan_dirs("normal", rebuild=self.rebuild)
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 249, in rescan_dirs
    files, streams, mtimes = self.get_files_list(
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 366, in get_files_list
    dir_files, dir_streams, dir_mtimes = self.get_files_list(
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 366, in get_files_list
    dir_files, dir_streams, dir_mtimes = self.get_files_list(
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 366, in get_files_list
    dir_files, dir_streams, dir_mtimes = self.get_files_list(
  [Previous line repeated 986 more times]
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 363, in get_files_list
    if self.is_hidden(path, entry=entry):
  File "/app/lib/python3.10/site-packages/pynicotine/shares.py", line 286, in is_hidden
    last_folder = os.path.basename(os.path.normpath(folder.replace('\\', '/')))
  File "/usr/lib/python3.10/posixpath.py", line 143, in basename
    sep = _get_sep(p)
  File "/usr/lib/python3.10/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I tried giving it all files permissions and linked the external drive folder, but nothing has changed.

**Comment by mathiascode** [comment]
Do you have a lot of nested folders (close to 1000) somewhere in your shares?

**Comment by sgreenden** [comment]
> Do you have a lot of nested folders (close to 1000) somewhere in your shares?

Nah, I have one folder with 600 items in it, the main folder is where the bulk of folders are
![image](https://github.com/nicotine-plus/nicotine-plus/assets/56249225/9fa6848a-c993-44d7-ade5-d0891d3b43bc)

**Comment by mathiascode** [comment]
Can you run the following command in a terminal and see if there's any output?

`find shared_folder -mindepth 500 -type d`

Replace `shared_folder` with the path to your shared folder.

**Comment by sgreenden** [comment]
There was no output 
![image](https://github.com/nicotine-plus/nicotine-plus/assets/56249225/d148b5cb-c048-4f5d-b967-c6249682066c)

**Comment by sgreenden** [comment]
The most depth that outputs is a 5
![image](https://github.com/nicotine-plus/nicotine-plus/assets/56249225/ae83f23a-0540-4bf1-ba78-930b955a099e)

**Comment by mathiascode** [comment]
That's strange, something in your shares must be hitting the recursion limit in some other way.

Could you check if this build works (see flatpak-package-x86_64 at the bottom of the page) and your shares look right after a rescan? https://github.com/nicotine-plus/nicotine-plus/actions/runs/5418373062?pr=2561

**Comment by sgreenden** [comment]
I get this error message 

```Nicotine+ Version: 3.3.0.dev5
GTK Version: 4.8.3
Python Version: 3.11.2 (linux)

Type: <class 'AttributeError'>
Value: 'gi.repository.Gtk' object has no attribute 'FontDialogButton'
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/dialogs/preferences.py", line 3062, in on_switch_page
    elif isinstance(obj, Gtk.FontButton) or GTK_API_VERSION >= 4 and isinstance(obj, Gtk.FontDialogButton):
                                                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (```

**Comment by sgreenden** [comment]
This version is working, thank you. 
![image](https://github.com/nicotine-plus/nicotine-plus/assets/56249225/064dac30-44cd-4aee-a55e-967db4230dae)

**Comment by mathiascode** [comment]
I checked your shares, this seems to be the problematic folder:
![](https://github.com/nicotine-plus/nicotine-plus/assets/8754153/1387b950-2458-40e7-8e4a-a61b5436673e)

I'll make some improvements to ensure backslashes in folder names don't mess up the scanner, but I suggest renaming the folder. Backslashes in folder/file names aren't currently supported.

**Comment by slook** [comment]
@sgreenden Switch to the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.3.0.dev5 to stay current with latest updates to the master branch. 

Thank you for your bug report.
