### ISSUE TITLE
error message whilst exiting n+

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#2610]
Nicotine+ version:  latest git
Operating System/Distribution: fedora 38

Whilst exiting n+ I get this error:
```
[2023-08-05 21:12:40] Quit Nicotine+ 3.3.0.dev5!
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/nicotine/src/nicotine-plus/pynicotine/gtkgui/widgets/theme.py", line 508, in on_icon_theme_changed
    load_custom_icons()
  File "/home/nicotine/src/nicotine-plus/pynicotine/gtkgui/widgets/theme.py", line 371, in load_custom_icons
    user_icon_theme_path = config.sections["ui"]["icontheme"]
                           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'icontheme'
```

**Comment by mathiascode** [comment]
Does 2c3caa6f5b697777be6aae2411a78c6c0cff669e fix the issue?

**Comment by hboetes** [comment]
Hard to check since it does not always happen, and I don't know how to reproduce it. Let's close the ticket for now and I'll reopen it if it reoccurs.

**Comment by mathiascode** [comment]
It should be fixed, the GTK side is shut down before the config module is cleared.

**Comment by stefantalpalaru** [comment]
I got this error with a recent Git HEAD build:

```text
Nicotine+ Version: 3.3.5.dev2
GTK Version: 4.14.4
Python Version: 3.12.4 (linux)

Type: <class 'KeyError'>
Value: 'icontheme'
Traceback:   File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/widgets/theme.py", line 396, in on_icon_theme_changed
    load_custom_icons()
  File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/widgets/theme.py", line 261, in load_custom_icons
    user_icon_theme_path = config.sections["ui"]["icontheme"]
                           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
```

I was not exiting the program. It did it on its own.

**Comment by mathiascode** [comment]
@stefantalpalaru Thanks, should be fixed now. Let us know if you still run into crashes.
