### ISSUE TITLE
Unable to add repo

### ISSUE THREAD

**Issue by yancyribbens** [nicotine-plus/nicotine-plus#2649]
Follow the instruction in:  https://nicotine-plus.org/doc/DOWNLOADS.html#gnulinux-bsd-solaris

```
sudo add-apt-repository ppa:nicotine-team/stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```

Current OS is Debian latest 12.1.

**Comment by mathiascode** [comment]
Did you run the first command, which installs python3-launchpadlib?

**Comment by mathiascode** [comment]
I'm assuming this is resolved, let me know if installing python3-launchpadlib didn't help.
