### ISSUE TITLE
crash after second run.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#267]
The first time I run nicotine it works fine. The second time I get the crash below.

Workaround: remove all files in ~/.local/share/nicotine
Platform: OpenBSD 6.7 amd64
Version: latest pull from git

```
Thu 07:58 Nicotine+ supports a country code blocker. This requires a (GPL'ed) library called GeoIP. You can find it here: C library:       https://github.com/maxmind/geoip-api-c Python
          bindings: https://github.com/maxmind/geoip-api-python (the python bindings require the C library)
Traceback (most recent call last):
  File "/usr/local/bin/nicotine", line 255, in <module>
    run()
  File "/usr/local/bin/nicotine", line 231, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 3595, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 273, in __init__
    config
  File "/usr/local/lib/python3.7/site-packages/pynicotine/pynicotine.py", line 130, in __init__
    self.shares = Shares(self)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 75, in __init__
    self.CompressShares("normal")
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 201, in CompressShares
    m.makeNetworkMessage(nozlib=0, rebuild=True)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1709, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by mathiascode** [comment]
Still investigating, but worst case scenario is that we have to replace shelves with something better...

**Comment by hboetes** [comment]
OK, poke me if you need a tester.

**Comment by mathiascode** [comment]
@hboetes Can you remove all files in ~/.local/share/nicotine again, and try this branch?

`git clone -b pickleproto https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
Hello @mathiascode,

I just tried again with the `pickleproto` branch and I got the same error, as a matter of fact, I got this error at shutdown.
 
```
reading from <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 2234)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2847, in OnBrowsePublicShares
    m.parseNetworkMessage(m.makeNetworkMessage(nozlib=1), nozlib=1)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1709, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by hboetes** [comment]
Hello @mathiascode 
I just tried it, it doesn't help, I still get the same output, I got this one as shutdown:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2809, in OnBrowsePublicShares
    m.parseNetworkMessage(m.makeNetworkMessage(nozlib=1), nozlib=1)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1710, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 1100, in OnGetShares
    self.BrowseUser(text)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2794, in BrowseUser
    self.OnBrowsePublicShares(None)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2809, in OnBrowsePublicShares
    m.parseNetworkMessage(m.makeNetworkMessage(nozlib=1), nozlib=1)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1710, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by mathiascode** [comment]
Bummer, can you try this branch?

`git clone -b simplelen https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
Nope :-(

This is what I get at startup:

```
% nicotine
Fri 13:43 Nicotine+ supports a country code blocker. This requires a (GPL'ed)
          library called GeoIP. You can find it here: C library:
          https://github.com/maxmind/geoip-api-c Python bindings:
          https://github.com/maxmind/geoip-api-python (the python bindings
          require the C library)
Fri 13:43 Unknown config option 'maximized' in section 'ui'
Traceback (most recent call last):
  File "/usr/local/bin/nicotine", line 276, in <module>
    run()
  File "/usr/local/bin/nicotine", line 252, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 3745, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 258, in __init__
    config
  File "/usr/local/lib/python3.7/site-packages/pynicotine/pynicotine.py", line 132, in __init__
    self.shares = Shares(self)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 74, in __init__
    self.CompressShares("normal")
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 199, in CompressShares
    m.makeNetworkMessage(nozlib=0, rebuild=True)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1710, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```
And I figured out that this message comes from browsing my public shares. Port 2234 is not blocked by the firewall.
```
reading from <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 2234)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2809, in OnBrowsePublicShares
    m.parseNetworkMessage(m.makeNetworkMessage(nozlib=1), nozlib=1)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1710, in makeNetworkMessage
    msg = msg + self.packObject(len(list(self.list.keys())))
  File "/usr/local/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
reading from <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 2234)>
```

**Comment by mathiascode** [comment]
Try cloning the branch again, line 1710 in slskmessages.py is not supposed to look like that anymore.

**Comment by mathiascode** [comment]
In fact, the whole country code blocker message shouldn't exist in either of my previous branches I posted here.

**Comment by hboetes** [comment]
@mathiascode 
You are absolutely right, I added branching code to my personal package manager, but had not ported that code to OpenBSD. Duh!

It's all fine and dandy now. Let's see if your branch also solves using a network share.

**Comment by hboetes** [comment]
Cried victory too soon. For testing purposes I added the smallest shared dir first, that went fine. After adding 2 more I ran into this. I'm going to rescan those three again from 0. I haven't even done the biggest 3 yet.
```
Traceback (most recent call last):
  File "/usr/local/bin/nicotine", line 241, in <module>
    run()
  File "/usr/local/bin/nicotine", line 217, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 3595, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 273, in __init__
    config
  File "/usr/local/lib/python3.7/site-packages/pynicotine/pynicotine.py", line 131, in __init__
    self.shares = Shares(self)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 75, in __init__
    self.CompressShares("normal")
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 201, in CompressShares
    m.makeNetworkMessage(nozlib=0, rebuild=True)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1710, in makeNetworkMessage
    for (key, value) in self.list.items():
  File "/usr/local/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
  File "/usr/local/lib/python3.7/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by mathiascode** [comment]
Any directory paths that are exceptionally long?

**Comment by mathiascode** [comment]
I'm not familiar with OpenBSD, but could you install python-gdbm somehow, if it's not already installed, and report back if it changed the situation in any way.

**Comment by hboetes** [comment]
I added another share which is bigger and it didn't have a problem with that one. On the one with problems I used `find . |awk '{ print length($0) " " $0; }' | sort -r -n |head` and the longest filename is 202 chars. What's the limit?

Let me add the gdbm module and see what happens.

**Comment by mathiascode** [comment]
That length seems normal. I suspect some specific file is causing issues. Can't give any better advice than to split the problematic share into smaller parts, to eventually isolate the issue.

**Comment by mathiascode** [comment]
If you end up finding the problematic file(s), I would be grateful if you could send them.

**Comment by hboetes** [comment]
I just tried again adding all my shares and now everything went fine. Go figure!
I still have the problematic `.local/share/nicotine` dir, would that help?

**Comment by mathiascode** [comment]
That would help. :)

**Comment by hboetes** [comment]
You've got mail!

**Comment by mathiascode** [comment]
I didn't find anything that looked suspicious. I suppose we can close this issue for now, and reopen if the problem reappears. The simplelen branch changes are in master now.

**Comment by hboetes** [comment]
You rock!
