### ISSUE TITLE
UPnP forwarding error: [Errno 126] Required key not available

### ISSUE THREAD

**Issue by pabateman** [nicotine-plus/nicotine-plus#2673]
Nicotine+ version:  3.2.9
Operating System/Distribution: Linux/Fedora 38 KDE

Nicotine+ comes from flatpak

### Describe the bug

Got an error right after start Nicotine+:

```
[2023-10-06 09:49:31] Loading GTK 3.24.38
[2023-10-06 09:49:31] Loading Python 3.11.5 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0]
[2023-10-06 09:49:31] Loading Nicotine+ 3.2.9
[2023-10-06 09:49:31] Listening on port: 2236
[2023-10-06 09:49:31] UPnP: Failed to forward external port 2236: [Errno 126] Required key not available
[2023-10-06 09:49:31] Loading plugin system
[2023-10-06 09:49:31] Rescanning shares…
[2023-10-06 09:49:31] 0 folders found before rescan, rebuilding…
[2023-10-06 09:49:31] Rescan complete: 0 folders found
[2023-10-06 09:49:31] Connecting to server.slsknet.org:2242
[2023-10-06 09:49:31] Connected to server server.slsknet.org:2242, logging in…
[2023-10-06 09:49:32] 1901 privileged users
[2023-10-06 09:49:32] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
```

And have no forwarded ports from Nicotine+ on my home router. Other software like Transmission forwards ports well.

Manual port forwarding works great, but it would be better to use dynamic port opening.

### Expected behavior

No `UPnP: Failed to forward external port 2236: [Errno 126] Required key not available` error and forwarded ports on my router.

### Steps to reproduce the bug

Just run Nicotine+ with flatpak:

```
flatpak run org.nicotine_plus.Nicotine
```

**Comment by slook** [comment]
Please can you test if forwarding works in the latest unstable build of Nicotine+ 3.3.0.dev5, link:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#flatpak

If it does, then no further action shall be required.

**Comment by mathiascode** [comment]
Please also enable Miscellaneous debug logging in 3.2.9 first, since the unstable build added NAT-PMP support, which might hide issues with UPnP.

**Comment by pabateman** [comment]
Hi. Done with both versions:

[3.2.9-misc-debug.log](https://github.com/nicotine-plus/nicotine-plus/files/12837829/3.2.9-misc-debug.log)

[3.3.0.dev5-misc-debug.log](https://github.com/nicotine-plus/nicotine-plus/files/12837830/3.3.0.dev5-misc-debug.log)

**Comment by mathiascode** [comment]
Thanks! I assume your system is fully up-to-date?

The error doesn't make much sense to me (sounds like a bug somewhere in the system), but I made a minor change to the way we send messages. Can you try the latest unstable build, both the Flatpak and running from [Git](https://nicotine-plus.org/doc/TESTING.html#git)?

**Comment by pabateman** [comment]
> I assume your system is fully up-to-date?

Yes, system is up to date.

```
$ uname -a 
Linux fedora 6.5.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 x86_64 GNU/Linux
```

> Can you try the latest unstable build, both the Flatpak and running from [Git](https://nicotine-plus.org/doc/TESTING.html#git)?

I tried both and got an errors again.  Files:

[3.3.0.dev5-misc-debug-git.log](https://github.com/nicotine-plus/nicotine-plus/files/12848783/3.3.0.dev5-misc-debug-git.log)
[3.3.0.dev5-misc-debug-flatpak.log](https://github.com/nicotine-plus/nicotine-plus/files/12848785/3.3.0.dev5-misc-debug-flatpak.log)

Git version has new NAT-PMP error.

Note, that UI was fully transparent on all dev versions. I'm not sure that it's broken, maybe that was dev-versions side effects. I would take screenshot, but there nothing to screen :) it's just no windows. I just see animations of minimize/maximize actions of invisible borders.

**Comment by mathiascode** [comment]
Does the `upnpc -l` command (provided by the miniupnpc package) list your forwarded ports without errors?

> Note, that UI was fully transparent on all dev versions. I'm not sure that it's broken, maybe that was dev-versions side effects. I would take screenshot, but there nothing to screen :) it's just no windows. I just see animations of minimize/maximize actions of invisible borders.

NVIDIA GPU? Can probably be worked around by switching to software rendering with the `GSK_RENDERER=cairo` env variable.

**Comment by mathiascode** [comment]
If you're planning on upgrading to Fedora 39, could you check if the issue still happens? I haven't spotted anything obviously wrong in our implementation so far, it doesn't do anything fancy compared to MiniUPnP.

**Comment by pabateman** [comment]
> If you're planning on upgrading to Fedora 39, could you check if the issue still happens? I haven't spotted anything obviously wrong in our implementation so far, it doesn't do anything fancy compared to MiniUPnP.

Ok I'll check right after upgrade.

**Comment by slook** [comment]
@pabateman Have you checked it is working now?

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#flatpak

**Comment by pabateman** [comment]
> @pabateman Have you checked it is working now?

I finally got around to this problem again.
I checked latest master build from flatpak package and there are still these errors:

```
[2023-12-23 14:49:04] [Misc] Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "/app/lib/python3.11/site-packages/pynicotine/upnp.py", line 311, in _update_port_mapping                                                                                                                                                                                                            
    service = self.find_service(self.local_ip_address)                                                                                                                                                                                                                                                      
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                      
  File "/app/lib/python3.11/site-packages/pynicotine/upnp.py", line 285, in find_service                                                                                                                                                                                                                    
    services = SSDP.get_services(private_ip)                                                                                                                                                                                                                                                                
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                
  File "/app/lib/python3.11/site-packages/pynicotine/upnp.py", line 178, in get_services                                                                                                                                                                                                                    
    wan_ip1.sendto(sock, (MULTICAST_HOST, MULTICAST_PORT))                                                                                                                                                                                                                                                  
  File "/app/lib/python3.11/site-packages/pynicotine/upnp.py", line 74, in sendto                                                                                                                                                                                                                           
    sock.sendto(msg, addr)                                                                                                                                                                                                                                                                                  
OSError: [Errno 126] Required key not available                                                                                                                                                                                                                                                             
```

But then I noticed that network interface selector was empty. I tried to set following values: 

- loopback interface
- dummy interface
- wifi adatper interface

UPnP works fine with loopback and wifi adapter and don't work with dummy interface (its network does not support UPnP according to error). And this actual for the latest stable build too.

So, if I leave wifi adapter in network interface selector then everything will be fine!

**Comment by mathiascode** [comment]
Nice catch! When no interface is set, Nicotine+ should get the current local IP address on the system, but I suppose something goes wrong there on your end.

Can you try the latest master? It logs the current network interface and local IP address when connecting to the server (in the Miscellaneous debug category). Can you check what IP address is reported when no interface is set, as well as for every interface?

**Comment by pabateman** [comment]
There is no messages about picked address:

[debug-3.3.0rc2-12-23.log](https://github.com/nicotine-plus/nicotine-plus/files/13760061/debug-3.3.0rc2-12-23.log)

Also when interface is set:

```
[2023-12-23 23:44:53] NAT-PMP: External port 2248 successfully forwarded to local IP address 192.168.x.x port 2248
```

My debug configuration:

```
...
[logging]
debug = True
debugmodes = ['miscellaneous']
...
```

**Comment by mathiascode** [comment]
It seems like you're one commit behind https://github.com/nicotine-plus/nicotine-plus/commit/b52c2574de5d81dad52af6f13f5e2e1350304887. Can you try downloading the latest build again?

**Comment by pabateman** [comment]
Yes, you're right, now I see the message: 

```
[2023-12-24 10:44:02] [Misc] Local IP address: 255.253.x.x
```

This is address of my wireguard interface (it always enabled). When I shut it off, then right address was picked: 

```
[2023-12-24 17:00:56] [Misc] Local IP address: 192.168.x.x
```

This is actual with every wireguard interface (I have many). It seems that wireguard always takes precedence over regular interface.

**Comment by mathiascode** [comment]
What are the Wireguard interfaces used for, are you using a VPN? Is all network traffic set to go through the interfaces, or do some applications like Transmission bypass it (since it was listed in the miniupnpc output)?

**Comment by pabateman** [comment]
> are you using a VPN?

I'm using Wireguard interfaces to access some private networks that are not in my home segment.

> you can set the network interface Nicotine+ uses if needed.

Yes, I'm got it!
It seems like false positive. So I'm closing the issue.

Best regards!
