### ISSUE TITLE
Nicotine 3.3.7 issue with Sonoma 14.7.2 : impossible to start app !

### ISSUE THREAD

**Issue by Chawaks** [nicotine-plus/nicotine-plus#3227]
Nicotine+ version:  3.3.7 ARM64 (Macbook Pro M1 Max)
Operating System/Distribution:
Sonoma 14.7.2 (recent setup, clean system)

### Describe the bug
The app crashes at launch, unable to start Nicotinre+, macOs don't return any crash.
Roll back to 3.3.6 : everything is fine, tha apps starts normally.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Please try the following:
- Open the downloaded .dmg file
- Right-click the Nicotine+ icon and select "Show package contents"
- Navigate to the `Contents/MacOS` folder
- Right-click the `Nicotine+` executable, and select the option to open in a terminal

What's the output in the terminal?

Assuming you tried the Apple Silicon/ARM64 version of Nicotine+, could you also try the Intel/x86_64 version and see if it works?

**Comment by wiggly-sheets** [comment]
Having the same issue on Sonoma 14.5 with a Macbook Air M2. Silicon version not working but Intel version is. 
Output from terminal when launching silicon executable: 

/Applications/Nicotine+\ copy.app/Contents/MacOS/Nicotine+ ; exit;
[12/17/2024 16:57:12] Loading Python 3.12.8
[12/17/2024 16:57:12] Loading Nicotine+ 3.3.7

** (process:28099): WARNING **: 16:57:12.107: Failed to load shared library '/opt/homebrew/Cellar/glib/2.82.3/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/opt/homebrew/Cellar/glib/2.82.3/lib/libgobject-2.0.0.dylib, 0x0009): tried: '/opt/homebrew/Cellar/glib/2.82.3/lib/libgobject-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/glib/2.82.3/lib/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/Cellar/glib/2.82.3/lib/libgobject-2.0.0.dylib' (no such file)
Traceback (most recent call last):
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/nicotine", line 39, in <module>
  File "/Users/runner/work/nicotine-plus/nicotine-plus/nicotine", line 35, in load_module
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 224, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 141, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 94, in check_gtk_version
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 147, in create_module
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/__init__.py", line 112, in load_overrides
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/GLib.py", line 699, in <module>
  File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/GLib.py", line 749, in IOChannel
AttributeError: type object 'Source' has no attribute 'SET'

Saving session...completed.

**Comment by mathiascode** [comment]
The download link for the Apple Silicon build has been reverted to 3.3.6 for now.

Does the latest development build work? https://nicotine-plus.org/doc/TESTING.html#macos

**Comment by wiggly-sheets** [comment]
> The download link for the Apple Silicon build has been reverted to 3.3.6 for now.
> 
> Does the latest development build work? [nicotine-plus.org/doc/TESTING.html#macos](https://nicotine-plus.org/doc/TESTING.html#macos)

I tried the unstable build earlier and experienced the same behavior as the stable build.

**Comment by mathiascode** [comment]
Could you try the unstable build again? Some packages were updated in the meantime, and I'd like to verify if this fixed the issue or not.

**Comment by wiggly-sheets** [comment]
> Could you try the unstable build again? Some packages were updated in the meantime, and I'd like to verify if this fixed the issue or not.

Upon trying 3.3.8 dev build the app does not crash like the prior dev build did (and like 3.3.7), but instead bounces endlessly in my dock in an unresponsive state. Only way to close it is to force quit. I let it bounce for a few minutes to see if it would launch but it did not.

**Comment by Chawaks** [comment]
Hi guys,

Just tried the latest dev build for ARM (https://nightly.link/nicotine-plus/nicotine-plus/workflows/packaging/master/macos-arm64-installer.zip)

Same behaviour as 3.3.7 ARM stable release : nothing happen.

Here's what terminal return on my MBP M1

[12/18/24 09:14:05] Loading Python 3.12.8

[12/18/24 09:14:05] Loading Nicotine+ 3.3.8.dev1

** (process:1213): WARNING **: 09:14:05.785: Failed to load shared library '/opt/homebrew/Cellar/glib/2.82.4/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/opt/homebrew/Cellar/glib/2.82.4/lib/libgobject-2.0.0.dylib, 0x0009): tried: '/opt/homebrew/Cellar/glib/2.82.4/lib/libgobject-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/glib/2.82.4/lib/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/Cellar/glib/2.82.4/lib/libgobject-2.0.0.dylib' (no such file)

Traceback (most recent call last):

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/cx_Freeze/initscripts/console.py", line 25, in run

File "/Users/runner/work/nicotine-plus/nicotine-plus/nicotine", line 39, in <module>

File "/Users/runner/work/nicotine-plus/nicotine-plus/nicotine", line 35, in load_module

File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 224, in run

File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 141, in run

File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 94, in check_gtk_version

File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 921, in _load_unlocked

File "<frozen importlib._bootstrap>", line 813, in module_from_spec

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module

File ***@***.***/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module

File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 921, in _load_unlocked

File "<frozen importlib._bootstrap>", line 813, in module_from_spec

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module

File ***@***.***/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module

File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 921, in _load_unlocked

File "<frozen importlib._bootstrap>", line 813, in module_from_spec

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module

File ***@***.***/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module

File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 921, in _load_unlocked

File "<frozen importlib._bootstrap>", line 813, in module_from_spec

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 146, in create_module

File ***@***.***/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module

File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 921, in _load_unlocked

File "<frozen importlib._bootstrap>", line 813, in module_from_spec

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/importer.py", line 147, in create_module

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/__init__.py", line 112, in load_overrides

File ***@***.***/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/GLib.py", line 699, in <module>

File "/Users/runner/work/nicotine-plus/nicotine-plus/venv/lib/python3.12/site-packages/gi/overrides/GLib.py", line 749, in IOChannel

AttributeError: type object 'Source' has no attribute 'SET'

Saving session...

...saving history...truncating history files...

...completed.

Deleting expired sessions...none found.

[Process completed]

Hope this helps !

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/mail/home)

**Comment by mathiascode** [comment]
The issue should be fixed in the latest unstable build. Let me know if it still fails.

**Comment by wiggly-sheets** [comment]
> The issue should be fixed in the latest unstable build. Let me know if it still fails.

Unstable build now working great! Thanks.

**Comment by Chawaks** [comment]
nicotine+-3.3.8.dev1 ARM version starts normally and seem to work great.
Thanks for your efforts, Nicotine is awesome.
