### ISSUE TITLE
AttributeError: 'Uploads' object has no attribute 'transfers'

### ISSUE THREAD

**Issue by toofar** [Nicotine-Plus/nicotine-plus#360]
Nicotine+ version:  git head 6199a0ddc619bbaab1b6f8211d936a0e8eb1a7df
Operating System/Distribution: debian a couple of version behind, running from source with all libraries required by the unstable PPA build installed.

### Describe the bug
See stack trace below, not sure there is anything it actually breaks.

### Expected behavior
No scary back traces!

### Steps to reproduce the bug
Umm, not sure. Probably have an upload start while the uploads pane is open, might need to be grouped. I can try to reproduce more if the stacktrace below isn't enough.

### Additional context
Sorry for the poor title, I'm not sure if this actually has any negative effect apart from the stack trace. It looks like TransferList.transferlist was removed in #337, maybe it should be something to do with self.frame.np.transfers? Also thank you for the performance improvements, my potate seedbox appreciates it.

```
Traceback (most recent call last):
  File "/home/user/projects/nicotine-plus/pynicotine/gtkgui/frame.py", line 1297, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/home/user/projects/nicotine-plus/pynicotine/pynicotine.py", line 1556, in QueueUpload
    self.transfers.QueueUpload(msg)
  File "/home/user/projects/nicotine-plus/pynicotine/transfers.py", line 700, in QueueUpload
    self._updateOrAppendUpload(user, msg.file, newupload)
  File "/home/user/projects/nicotine-plus/pynicotine/transfers.py", line 614, in _updateOrAppendUpload
    self.uploadspanel.replace(i, transferobj)
  File "/home/user/projects/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 293, in replace
    for i in self.transfers:
AttributeError: 'Uploads' object has no attribute 'transfers'
Traceback (most recent call last):
  File "/home/user/projects/nicotine-plus/pynicotine/gtkgui/frame.py", line 1297, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/home/user/projects/nicotine-plus/pynicotine/pynicotine.py", line 1556, in QueueUpload
    self.transfers.QueueUpload(msg)
  File "/home/user/projects/nicotine-plus/pynicotine/transfers.py", line 700, in QueueUpload
    self._updateOrAppendUpload(user, msg.file, newupload)
  File "/home/user/projects/nicotine-plus/pynicotine/transfers.py", line 614, in _updateOrAppendUpload
    self.uploadspanel.replace(i, transferobj)
  File "/home/user/projects/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 293, in replace
    for i in self.transfers:
AttributeError: 'Uploads' object has no attribute 'transfers'
```

**Comment by kiplingw** [comment]
@toofar, thank you for reporting. Would you be able to test the latest unstable package from the PPA? This looks like a syntax error, but I'd just like to rule out any other issues that might have arisen from running from source. A new package should be injected into the repository within the next 45 minutes or so. It's currently building now.

**Comment by mathiascode** [comment]
I have a fix ready, will create a PR shortly.
