### ISSUE TITLE
this hangs the program since a few days, I'm using the git head version

### ISSUE THREAD

**Issue by ghost** [Nicotine-Plus/nicotine-plus#4]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/user/opt/nicotine/pynicotine/slskproto.py", line 385, in run
    conns, connsinprogress, server_socket = self.process_queue(queue, conns, connsinprogress, server_socket)
  File "/home/user/opt/nicotine/pynicotine/slskproto.py", line 919, in process_queue
    msg = msgObj.makeNetworkMessage()
  File "/home/user/opt/nicotine/pynicotine/slskmessages.py", line 1763, in makeNetworkMessage
    self.packObject(2) +
  File "/home/user/opt/nicotine/pynicotine/slskmessages.py", line 304, in packObject
    return struct.pack("<I", object.value)
error: integer out of range for 'I' format code

/home/user/opt/nicotine/pynicotine/gtkgui/frame.py:1295: Warning: Source ID 27653 was not found when attempting to remove it
  gobject.source_remove(self.awaytimer)

**Comment by Mutnick** [comment]
ghost it would be good to know if this is still an issue, have you run from recent source?

**Comment by gfarmerfr** [comment]
This issue seems to be fixed in master, also the user that reported this bug is not on github anymore.
Closing this issue.
