### ISSUE TITLE
progress bar stuck at 100%

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#454]
During a rescan of my collection I noticed the progress bar got stuck at 100%, where it would usually disappear, and I found this trace message in the console:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'Klassiek\\Jean Sibelius\\Two Serenades for Violin and Orchestra, Op.69'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 2039, in _RescanFinished
    self.np.shares.sendNumSharedFoldersFiles()
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 105, in sendNumSharedFoldersFiles
    sharedfiles = sum([len(x) for x in list(conf["transfers"][shared_db].values())])
  File "/usr/local/lib/python3.7/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/usr/local/lib/python3.7/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
  File "/usr/local/lib/python3.7/shelve.py", line 70, in closed
    raise ValueError('invalid operation on closed shelf')
ValueError: invalid operation on closed shelf

```
This problem is repeatable. I can't say I see anything odd in that directory.

**Comment by mathiascode** [comment]
Thanks, I can reproduce the issue. Doesn't happen consistently.
