### ISSUE TITLE
stacktrace: struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#527]
This error just popped up in the terminal from which I started N+
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskproto.py", line 552, in run
    conns, connsinprogress, server_socket = self.process_queue(queue, conns, connsinprogress, server_socket)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskproto.py", line 1134, in process_queue
    msg = msgObj.makeNetworkMessage()
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1877, in makeNetworkMessage
    self.packObject(1) +
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 277, in packObject
    return struct.pack("<I", object.value)
struct.error: required argument is not an integer
```

**Comment by hboetes** [comment]
Issue has been resolved with #528 indeed.
