### ISSUE TITLE
Chat messages went nowhere and I got this trace.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#545]
With the latest release all of a sudden chat stopped working, what I typed didn't show up, and I got this trace.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskproto.py", line 554, in run
    conns, connsinprogress, server_socket = self.process_queue(queue, conns, connsinprogress, server_socket)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskproto.py", line 1141, in process_queue
    msg = msgObj.makeNetworkMessage()
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 1918, in makeNetworkMessage
    msg.extend(self.packObject(self.token))
  File "/usr/local/lib/python3.7/site-packages/pynicotine/slskmessages.py", line 250, in packObject
    return struct.pack("<i", object)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```
Version: c91c89a5d1003ed42cbb7e99813ca3b61d1ce767

**Comment by hboetes** [comment]
Testing #546

**Comment by hboetes** [comment]
Now I get a new trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 1170, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/pynicotine.py", line 1694, in DistribSearch
    self.shares.processSearchRequest(msg.searchterm, msg.user, msg.searchid, 0)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/shares.py", line 332, in processSearchRequest
    if i in wordindex:
  File "/usr/local/lib/python3.7/shelve.py", line 102, in __contains__
    return key.encode(self.keyencoding) in self.dict
  File "/usr/local/lib/python3.7/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/local/lib/python3.7/shelve.py", line 70, in closed
    raise ValueError('invalid operation on closed shelf')
ValueError: invalid operation on closed shelf
```
