### ISSUE TITLE
db file corruption?

### ISSUE THREAD

**Issue by starenka** [Nicotine-Plus/nicotine-plus#618]
Nicotine+ version:  master
Operating System/Distribution: Debian

```

starenka /opt/nicotine-plus at 5391714b? % /opt/nicotine-plus/.env/bin/python /opt/nicotine-plus/nicotine
Traceback (most recent call last):
  File "/usr/lib/python3.8/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'music\\Afx\\[2006] Chosen Lords'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nicotine-plus/nicotine", line 242, in <module>
    run()
  File "/opt/nicotine-plus/nicotine", line 218, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/opt/nicotine-plus/pynicotine/gtkgui/frame.py", line 3471, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/opt/nicotine-plus/pynicotine/gtkgui/frame.py", line 146, in __init__
    self.np = NetworkEventProcessor(
  File "/opt/nicotine-plus/pynicotine/pynicotine.py", line 133, in __init__
    self.shares = Shares(self)
  File "/opt/nicotine-plus/pynicotine/shares.py", line 71, in __init__
    self.CompressShares("normal")
  File "/opt/nicotine-plus/pynicotine/shares.py", line 197, in CompressShares
    m.makeNetworkMessage(nozlib=0, rebuild=True)
  File "/opt/nicotine-plus/pynicotine/slskmessages.py", line 1766, in makeNetworkMessage
    for (key, value) in self.list.items():
  File "/opt/nicotine-plus/.env/lib/python3.8/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib/python3.8/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
_dbm.error
```
I removed all db files from `~/.local/share/nicotine` to start nicotine. It happened to me before couple times ;(

**Comment by mathiascode** [comment]
Can you verify that you're actually on the latest master commit? That looks like a version from July or earlier, which doesn't include the file scanning improvements made at the beginning of August.

**Comment by starenka** [comment]
I'm sorry I just pulled but i was on 2.0.1 tag `commit 5391714b45d3a27991aa080fb0fe138a9d9eedd4 (HEAD, tag: 2.0.1)`... switching to master, now. :crossed_fingers: 

Sorry. I'm closing this issue now, okay?

**Comment by mathiascode** [comment]
Thank you! If you still encounter this issue in the future, feel free to open a new issue. :)
