### ISSUE TITLE
Compile pytaglib for Python 2 or 3? - Error Trying To Run 2.1.1

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#726]
Nicotine+ version:  2.11
Operating System/Distribution: Slackware 14.2 x86_64 

System apps:
python3-3.7.2
taglib-1.10

### Describe the bug
I'm assuming for now that I need to compile pytaglib for python3?

### Expected behavior
Have 2.1.1 run when I start it...

### Steps to reproduce the bug
When I run nicotine 2.1.1 against pytaglib-1.4.6 built against python3 I get this message at the terminal;

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/pynicotine/config.py", line 88, in __init__
    self.parser.read([self.filename], encoding="utf-8")
  File "/usr/lib64/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.7/configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 1634: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 3034, in OnActivate
    port
  File "/usr/lib64/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 126, in __init__
    config
  File "/usr/lib64/python3.7/site-packages/pynicotine/pynicotine.py", line 111, in __init__
    self.config = Config(config, data_dir)
  File "/usr/lib64/python3.7/site-packages/pynicotine/config.py", line 91, in __init__
    self.parser.read([self.filename], encoding="utf-8")
  File "/usr/lib64/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.7/configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 1634: invalid continuation byte

```P.S. Is nicotine suppose to be built against Python 2 or 3, I forget?```

**Comment by mathiascode** [comment]
Python 2 is no longer used in Nicotine+, and it seems like pytaglib is working fine for you. Looks like there is a problem loading the config file. Can you install python3-chardet if it's not already installed, and attempt to start Nicotine+ again?

**Comment by 0pLuS0** [comment]
Hi,

Ahh it's working now! 👍 

The only change I saw listed on the website News section was for pytaglib, I didn't see any mention of python3-chardet.

I went back and checked the website and on Github, I still no mention of this as a new dependency.

Can someone please add into either the website, or Github, or both a ```Dependencies``` section for building, so we'll know what is needed in the future?

THANKS

**Comment by mathiascode** [comment]
The python3-chardet dependency is only necessary once for converting an old config file to UTF-8, which I assumed was only needed on Windows. Since virtually every other OS defaults to UTF-8, and we haven't received more reports like this, I've opted to just show an error message about installing chardet in Nicotine+ 2.1.2.

**Comment by 0pLuS0** [comment]
But I hope in the future, if things change, there can be a ```Dependencies``` listed added somewhere...

THANKS
