### ISSUE TITLE
App won't start on MacOS Big Sur

### ISSUE THREAD

**Issue by asiufy** [Nicotine-Plus/nicotine-plus#880]
Nicotine+ version:  
Operating System/Distribution: MacOS 11.0.1 Big Sur (20B29)

### Describe the bug
App won't open. 

### Expected behavior
App opens.

### Steps to reproduce the bug
Double click on app or run from Terminal

### Additional context
Screenshots, logs, stacktraces or relevant information.
Output from Terminal:

[2020-11-30 00:53:44] Unknown config option 'totalqueue' in section 'transfers'
[2020-11-30 00:53:44] Unknown config option 'totalqueuelimit' in section 'transfers'
Traceback (most recent call last):
  File "pynicotine/gtkgui/frame.py", line 3008, in on_activate
  File "pynicotine/gtkgui/frame.py", line 369, in __init__
  File "pynicotine/gtkgui/userlist.py", line 144, in __init__
ValueError: not enough values to unpack (expected 7, got 4)
Traceback (most recent call last):
  File "pynicotine/gtkgui/frame.py", line 2591, in update_log
AttributeError: 'NicotineFrame' object has no attribute 'tag_log'

**Comment by kiplingw** [comment]
Thanks for reporting, @asiufy. This (hopefully) isn't related to your bug report, but since you are using Big Sur you might find [this](https://sneak.berlin/20201112/your-computer-isnt-yours/) of interest.

**Comment by mathiascode** [comment]
Is this an issue on the latest unstable build? https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/390794488

**Comment by asiufy** [comment]
mathiascode,

It starts up on the latest unstable build. But doesn't seem to connect or work properly. The Preference panel won't come up, for instance.

Thanks, I'll keep monitoring the new builds.

**Comment by mathiascode** [comment]
Thank you, could you post the terminal output if there's any?

**Comment by mathiascode** [comment]
Is this still an issue in the latest development builds?
